services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # 其他后端环境变量，如 API KEY 等
    ports:
      - 8000
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env:
      VITE_API_URL: http://backend:8000
      # 其他前端环境变量
    ports:
      - 5173
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - 6379
